### ISSUE TITLE
Split-K Matmul Lowering via `lowering_config.tile_sizes`

### ISSUE THREAD

**Issue by manishucsd** [iree-org/iree#13014]
### Request description

IREE Codegen triggers split-k in Flow dialect by passing additional tile configuration dimension: 
`lowering_config = <tile_sizes = [[64, 64, 64]]>` to ` lowering_config = <tile_sizes = [[1, 64, 64, 64]]>` . The API to trigger split-k should be simpler and intuitive. Please review the current state of API to enable split-k matmul and the proposal at the end.

# Current API for Split-K Matmul Support
We are using tile_size's additional dim as way to communicate that it is a split-k matmul. Please notice that the only thing changing the `Matmul` and `Split-k Matmul` IR below is the `lowering_cong.tile_size`.

### Matmul 
```mlir
#tile_config_64x64_64x5_tensorcore_mmasync = #iree_codegen.compilation_info<
  lowering_config = <tile_sizes = [[64, 64, 64]]>,
  translation_info = <LLVMGPUMatmulTensorCoreMmaSync pipeline_depth = 5>,
  workgroup_size = [64 : index, 2 : index, 1 : index]
>

// Dispatch linalg.matmul row-row layout 
func.func @matmul_128x128x12288_f16t_f16t_f16t_tile_config_64x64_64x5_tensorcore_mmasync(
  %lhs: tensor<128x12288xf16>,
  %rhs: tensor<12288x128xf16>) -> tensor<128x128xf16>
{
  %c0 = arith.constant 0.0 : f16
  %init = tensor.empty() : tensor<128x128xf16>
  %inital_result = linalg.fill ins(%c0 : f16) outs(%init : tensor<128x128xf16>) -> tensor<128x128xf16>
  %result = linalg.matmul {compilation_info = #tile_config_64x64_64x5_tensorcore_mmasync} 
                     ins(%lhs, %rhs: tensor<128x12288xf16>, tensor<12288x128xf16>)
                     outs(%inital_result: tensor<128x128xf16>) -> tensor<128x128xf16>
  return %result : tensor<128x128xf16>
}
```

### Split-k Matmul
```mlir
#tile_config_64x64_64x5_tensorcore_mmasync = #iree_codegen.compilation_info<
  lowering_config = <tile_sizes = [[1, 64, 64, 64]]>,
  translation_info = <LLVMGPUMatmulTensorCoreMmaSync pipeline_depth = 5>,
  workgroup_size = [64 : index, 2 : index, 1 : index]
>

// Dispatch linalg.matmul row-row layout 
func.func @matmul_128x128x12288_f16t_f16t_f16t_tile_config_64x64_64x5_tensorcore_mmasync(
  %lhs: tensor<128x12288xf16>,
  %rhs: tensor<12288x128xf16>) -> tensor<128x128xf16>
{
  %c0 = arith.constant 0.0 : f16
  %init = tensor.empty() : tensor<128x128xf16>
  %inital_result = linalg.fill ins(%c0 : f16) outs(%init : tensor<128x128xf16>) -> tensor<128x128xf16>
  %result = linalg.matmul {compilation_info = #tile_config_64x64_64x5_tensorcore_mmasync} 
                     ins(%lhs, %rhs: tensor<128x12288xf16>, tensor<12288x128xf16>)
                     outs(%inital_result: tensor<128x128xf16>) -> tensor<128x128xf16>
  return %result : tensor<128x128xf16>
}
```

We should have better API to enable split-k in IREE codegen. Ideally, it will be great if `split-k-slice` or `split-ratio` be a runtime argument to the kernel and we can sweep through various `split-ratio` or we will have to generate one different kernel for different `split-ratio` for the same matmul. 

# Proposal for Intuitive API for Split-K Matmul Support
Adding `split_ratio = SPLIT_RATIO` and `split_mode = [SERIAL | PARALLEL]` in `translation_info` will be more intuitive. For now, we only support split_mode as PARALLEL, but serail split-k maybe helpful for some use cases and maybe we want to support in the future. 

Please an example below:
```mlir
#tile_config_64x64_64x5_tensorcore_mmasync = #iree_codegen.compilation_info<
  lowering_config = <tile_sizes = [[64, 64, 64]]>,
  translation_info = <LLVMGPUMatmulTensorCoreMmaSync pipeline_depth = 5 split_mode = parallel split_ratio = 16>,
  workgroup_size = [64 : index, 2 : index, 1 : index]
>

// Dispatch linalg.matmul row-row layout 
func.func @matmul_128x128x12288_f16t_f16t_f16t_tile_config_64x64_64x5_tensorcore_mmasync(
  %lhs: tensor<128x12288xf16>,
  %rhs: tensor<12288x128xf16>) -> tensor<128x128xf16>
{
  %c0 = arith.constant 0.0 : f16
  %init = tensor.empty() : tensor<128x128xf16>
  %inital_result = linalg.fill ins(%c0 : f16) outs(%init : tensor<128x128xf16>) -> tensor<128x128xf16>
  %result = linalg.matmul {compilation_info = #tile_config_64x64_64x5_tensorcore_mmasync} 
                     ins(%lhs, %rhs: tensor<128x12288xf16>, tensor<12288x128xf16>)
                     outs(%inital_result: tensor<128x128xf16>) -> tensor<128x128xf16>
  return %result : tensor<128x128xf16>
}
```

**Comment by allieculp** [comment]
From triage meeting: @manishucsd looks like this is in progress?

**Comment by manishucsd** [comment]
@allieculp , We have identified this issue and this is not in progress. I created this issue so as to have discussion on this and track what decision we make to handle this. As I understand, the solution to this may not be trivial. 

cc: @ThomasRaoux , @julianwa, @MaheshRavishankar

**Comment by allieculp** [comment]
Got it, thanks Manish. Sounds like we need some triage here to determine the priority of this issue and next steps.
@mattwalsh for visibility

**Comment by MaheshRavishankar** [comment]
> IREE Codegen triggers split-k in Flow dialect by passing additional tile configuration dimension:
> `lowering_config = <tile_sizes = [[64, 64, 64]]>` to ` lowering_config = <tile_sizes = [[1, 64, 64, 64]]>`

This is actually not great. The attribute is meant to be completely pass-through for Flow. The fact that this is happening should be fixed (I missed that this is actually what is happening in the split-k pass, but I mostly dont keep track of things happening in the split-k pass).

> We should have better API to enable split-k in IREE codegen. Ideally, it will be great if `split-k-slice` or `split-ratio` be a runtime argument to the kernel and we can sweep through various `split-ratio` or we will have to generate one different kernel for different `split-ratio` for the same matmul.

Having a runtime argument would indeed be great.... There is some work in the code-generation though that will need to happen to make this work.... Right now the split-k pass is breaking layering in Flow, and if it needs to exist at the place it is today, then fixing that would be a good place to start. There is some non-trivial amount of work to be done for getting split-k working in a way that does not break the Flow layering, and will also allow the split-k value to be a runtime value. (I am intentionally avoiding the details, but if there is interest I can write that up), but I think would be worth investing in. Things built on top of existing split-k path is hard to support in the long run.

**Comment by ThomasRaoux** [comment]
> > IREE Codegen triggers split-k in Flow dialect by passing additional tile configuration dimension:
> > `lowering_config = <tile_sizes = [[64, 64, 64]]>` to ` lowering_config = <tile_sizes = [[1, 64, 64, 64]]>`
> 
> This is actually not great. The attribute is meant to be completely pass-through for Flow. The fact that this is happening should be fixed (I missed that this is actually what is happening in the split-k pass, but I mostly dont keep track of things happening in the split-k pass).

How would you fix it? The problem is that at the flow level we cannot modify the lowering config and the split k will convert the matmul in a batch_matmul therefore we need the extra tiling dim for the batch. It would be great to fix but I haven't been able to find a solution with current path.

> 
> > We should have better API to enable split-k in IREE codegen. Ideally, it will be great if `split-k-slice` or `split-ratio` be a runtime argument to the kernel and we can sweep through various `split-ratio` or we will have to generate one different kernel for different `split-ratio` for the same matmul.
> 
> Having a runtime argument would indeed be great.... There is some work in the code-generation though that will need to happen to make this work.... Right now the split-k pass is breaking layering in Flow, and if it needs to exist at the place it is today, then fixing that would be a good place to start. There is some non-trivial amount of work to be done for getting split-k working in a way that does not break the Flow layering, and will also allow the split-k value to be a runtime value. (I am intentionally avoiding the details, but if there is interest I can write that up), but I think would be worth investing in. Things built on top of existing split-k path is hard to support in the long run.

I know this is something we discussed before but I don't recall a practical solution to the problem that split-k needs to happen before dispatch region formation. Is your solution to do this in pre-processing? Or is there another alternative?

**Comment by allieculp** [comment]
Can be closed by #13115 ?

**Comment by manishucsd** [comment]
We have decent confidence that we can get performance of split-k matmul to match the library/cuBLAS performance, but there are a two issues in path to production: 

- [x] 1. An intuitive split-k API which does NOT use batch_matmul as a proxy to trigger split-k ([#13014](https://github.com/openxla/iree/issues/13014) - Issue closed but not fixed )  **[This issue]**
- [ ] 2. Relaxing the restrictions on the reduction dim to be divisible by split-ratio ([#13015](https://github.com/openxla/iree/issues/13015) - Issue closed but not fixed)

**Note:** We are trying to feed two bird with one seed by the solution proposed in [#13155](https://github.com/openxla/iree/issues/13115)

The above two issue is being handled in the discussion and solutions proposed here [#13155](https://github.com/openxla/iree/issues/13115) (Open issue and addressing 1. And 2. from path to production).
